name: MacOs

on: push

jobs:
  build:
    name: MacOs ${{ matrix.cc }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        cc: [gcc, clang]

    steps:

    - name: Dependencies
      if: "${{ matrix.cc == 'clang' }}"
      run: brew install llvm

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: ${{ matrix.cc }} -Wall -Wextra compile.c

    - name: Test
      run: PATH="bin:$PATH" ./a.out test
